#!/bin/sh

ln -s /homes/egarnick/output/counts/uzb.0.counts inputs-uzb_vectors/counts/uzb.0.counts
ln -s /homes/egarnick/output/counts/uzb.1.counts inputs-uzb_vectors/counts/uzb.1.counts
ln -s /homes/egarnick/output/counts/uzb.2.counts inputs-uzb_vectors/counts/uzb.2.counts
ln -s /homes/egarnick/output/counts/uzb.3.counts inputs-uzb_vectors/counts/uzb.3.counts
ln -s /homes/egarnick/output/counts/uzb.4.counts inputs-uzb_vectors/counts/uzb.4.counts
ln -s /homes/egarnick/output/counts/uzb.5.counts inputs-uzb_vectors/counts/uzb.5.counts
ln -s /homes/egarnick/output/counts/uzb.6.counts inputs-uzb_vectors/counts/uzb.6.counts
ln -s /homes/egarnick/output/counts/uzb.7.counts inputs-uzb_vectors/counts/uzb.7.counts
ln -s /homes/egarnick/output/counts/uzb.8.counts inputs-uzb_vectors/counts/uzb.8.counts
ln -s /homes/egarnick/output/counts/uzb.9.counts inputs-uzb_vectors/counts/uzb.9.counts
ln -s /homes/egarnick/output/counts/uzb.10.counts inputs-uzb_vectors/counts/uzb.10.counts
ln -s /homes/egarnick/output/counts/uzb.11.counts inputs-uzb_vectors/counts/uzb.11.counts
ln -s /homes/egarnick/output/counts/uzb.12.counts inputs-uzb_vectors/counts/uzb.12.counts
ln -s /homes/egarnick/output/counts/uzb.13.counts inputs-uzb_vectors/counts/uzb.13.counts
ln -s /homes/egarnick/output/counts/uzb.14.counts inputs-uzb_vectors/counts/uzb.14.counts
ln -s /homes/egarnick/output/counts/uzb.15.counts inputs-uzb_vectors/counts/uzb.15.counts
ln -s /homes/egarnick/output/counts/uzb.16.counts inputs-uzb_vectors/counts/uzb.16.counts
ln -s /homes/egarnick/output/counts/uzb.17.counts inputs-uzb_vectors/counts/uzb.17.counts
ln -s /homes/egarnick/output/counts/uzb.18.counts inputs-uzb_vectors/counts/uzb.18.counts
ln -s /homes/egarnick/output/counts/uzb.19.counts inputs-uzb_vectors/counts/uzb.19.counts
ln -s /homes/egarnick/output/counts/uzb.20.counts inputs-uzb_vectors/counts/uzb.20.counts
ln -s /homes/egarnick/output/counts/uzb.21.counts inputs-uzb_vectors/counts/uzb.21.counts
ln -s /homes/egarnick/output/counts/uzb.22.counts inputs-uzb_vectors/counts/uzb.22.counts
ln -s /homes/egarnick/output/counts/uzb.23.counts inputs-uzb_vectors/counts/uzb.23.counts
ln -s /homes/egarnick/output/counts/uzb.24.counts inputs-uzb_vectors/counts/uzb.24.counts
ln -s /homes/egarnick/output/counts/uzb.25.counts inputs-uzb_vectors/counts/uzb.25.counts
ln -s /homes/egarnick/output/counts/uzb.26.counts inputs-uzb_vectors/counts/uzb.26.counts
ln -s /homes/egarnick/output/counts/uzb.27.counts inputs-uzb_vectors/counts/uzb.27.counts
ln -s /homes/egarnick/output/counts/uzb.28.counts inputs-uzb_vectors/counts/uzb.28.counts
ln -s /homes/egarnick/output/counts/uzb.29.counts inputs-uzb_vectors/counts/uzb.29.counts
ln -s /homes/egarnick/output/counts/uzb.30.counts inputs-uzb_vectors/counts/uzb.30.counts
ln -s /homes/egarnick/output/counts/uzb.31.counts inputs-uzb_vectors/counts/uzb.31.counts
ln -s /homes/egarnick/output/counts/uzb.32.counts inputs-uzb_vectors/counts/uzb.32.counts
ln -s /homes/egarnick/output/counts/uzb.33.counts inputs-uzb_vectors/counts/uzb.33.counts
ln -s /homes/egarnick/output/counts/uzb.34.counts inputs-uzb_vectors/counts/uzb.34.counts
ln -s /homes/egarnick/output/counts/uzb.35.counts inputs-uzb_vectors/counts/uzb.35.counts
ln -s /homes/egarnick/output/counts/uzb.36.counts inputs-uzb_vectors/counts/uzb.36.counts
ln -s /homes/egarnick/output/counts/uzb.37.counts inputs-uzb_vectors/counts/uzb.37.counts
ln -s /homes/egarnick/output/counts/uzb.38.counts inputs-uzb_vectors/counts/uzb.38.counts
ln -s /homes/egarnick/output/counts/uzb.39.counts inputs-uzb_vectors/counts/uzb.39.counts
ln -s /homes/egarnick/output/counts/uzb.40.counts inputs-uzb_vectors/counts/uzb.40.counts
ln -s /homes/egarnick/output/counts/uzb.41.counts inputs-uzb_vectors/counts/uzb.41.counts
ln -s /homes/egarnick/output/counts/uzb.42.counts inputs-uzb_vectors/counts/uzb.42.counts
ln -s /homes/egarnick/output/counts/uzb.43.counts inputs-uzb_vectors/counts/uzb.43.counts
ln -s /homes/egarnick/output/counts/uzb.44.counts inputs-uzb_vectors/counts/uzb.44.counts
ln -s /homes/egarnick/output/counts/uzb.45.counts inputs-uzb_vectors/counts/uzb.45.counts
ln -s /homes/egarnick/output/counts/uzb.46.counts inputs-uzb_vectors/counts/uzb.46.counts
ln -s /homes/egarnick/output/counts/uzb.47.counts inputs-uzb_vectors/counts/uzb.47.counts
ln -s /homes/egarnick/output/counts/uzb.48.counts inputs-uzb_vectors/counts/uzb.48.counts
ln -s /homes/egarnick/output/counts/uzb.49.counts inputs-uzb_vectors/counts/uzb.49.counts
ln -s /homes/egarnick/output/counts/uzb.50.counts inputs-uzb_vectors/counts/uzb.50.counts
ln -s /homes/egarnick/output/counts/uzb.51.counts inputs-uzb_vectors/counts/uzb.51.counts
ln -s /homes/egarnick/output/counts/uzb.52.counts inputs-uzb_vectors/counts/uzb.52.counts
ln -s /homes/egarnick/output/counts/uzb.53.counts inputs-uzb_vectors/counts/uzb.53.counts
ln -s /homes/egarnick/output/counts/uzb.54.counts inputs-uzb_vectors/counts/uzb.54.counts
ln -s /homes/egarnick/output/counts/uzb.55.counts inputs-uzb_vectors/counts/uzb.55.counts
ln -s /homes/egarnick/output/counts/uzb.56.counts inputs-uzb_vectors/counts/uzb.56.counts
ln -s /homes/egarnick/output/counts/uzb.57.counts inputs-uzb_vectors/counts/uzb.57.counts
ln -s /homes/egarnick/output/counts/uzb.58.counts inputs-uzb_vectors/counts/uzb.58.counts
ln -s /homes/egarnick/output/counts/uzb.59.counts inputs-uzb_vectors/counts/uzb.59.counts
ln -s /homes/egarnick/output/counts/uzb.60.counts inputs-uzb_vectors/counts/uzb.60.counts
ln -s /homes/egarnick/output/counts/uzb.61.counts inputs-uzb_vectors/counts/uzb.61.counts
ln -s /homes/egarnick/output/counts/uzb.62.counts inputs-uzb_vectors/counts/uzb.62.counts
ln -s /homes/egarnick/output/counts/uzb.63.counts inputs-uzb_vectors/counts/uzb.63.counts
ln -s /homes/egarnick/output/counts/uzb.64.counts inputs-uzb_vectors/counts/uzb.64.counts
ln -s /homes/egarnick/output/counts/uzb.65.counts inputs-uzb_vectors/counts/uzb.65.counts
ln -s /homes/egarnick/output/counts/uzb.66.counts inputs-uzb_vectors/counts/uzb.66.counts
ln -s /homes/egarnick/output/counts/uzb.67.counts inputs-uzb_vectors/counts/uzb.67.counts
ln -s /homes/egarnick/output/counts/uzb.68.counts inputs-uzb_vectors/counts/uzb.68.counts
ln -s /homes/egarnick/output/counts/uzb.69.counts inputs-uzb_vectors/counts/uzb.69.counts
ln -s /homes/egarnick/output/counts/uzb.70.counts inputs-uzb_vectors/counts/uzb.70.counts
ln -s /homes/egarnick/output/counts/uzb.71.counts inputs-uzb_vectors/counts/uzb.71.counts
ln -s /homes/egarnick/output/counts/uzb.72.counts inputs-uzb_vectors/counts/uzb.72.counts
ln -s /homes/egarnick/output/counts/uzb.73.counts inputs-uzb_vectors/counts/uzb.73.counts
ln -s /homes/egarnick/output/counts/uzb.74.counts inputs-uzb_vectors/counts/uzb.74.counts
ln -s /homes/egarnick/output/counts/uzb.75.counts inputs-uzb_vectors/counts/uzb.75.counts
ln -s /homes/egarnick/output/counts/uzb.76.counts inputs-uzb_vectors/counts/uzb.76.counts
ln -s /homes/egarnick/output/counts/uzb.77.counts inputs-uzb_vectors/counts/uzb.77.counts
ln -s /homes/egarnick/output/counts/uzb.78.counts inputs-uzb_vectors/counts/uzb.78.counts
ln -s /homes/egarnick/output/counts/uzb.79.counts inputs-uzb_vectors/counts/uzb.79.counts
ln -s /homes/egarnick/output/counts/uzb.80.counts inputs-uzb_vectors/counts/uzb.80.counts
ln -s /homes/egarnick/output/counts/uzb.81.counts inputs-uzb_vectors/counts/uzb.81.counts
ln -s /homes/egarnick/output/counts/uzb.82.counts inputs-uzb_vectors/counts/uzb.82.counts
ln -s /homes/egarnick/output/counts/uzb.83.counts inputs-uzb_vectors/counts/uzb.83.counts
ln -s /homes/egarnick/output/counts/uzb.84.counts inputs-uzb_vectors/counts/uzb.84.counts
ln -s /homes/egarnick/output/counts/uzb.85.counts inputs-uzb_vectors/counts/uzb.85.counts
ln -s /homes/egarnick/output/counts/uzb.86.counts inputs-uzb_vectors/counts/uzb.86.counts
ln -s /homes/egarnick/output/counts/uzb.87.counts inputs-uzb_vectors/counts/uzb.87.counts
ln -s /homes/egarnick/output/counts/uzb.88.counts inputs-uzb_vectors/counts/uzb.88.counts
ln -s /homes/egarnick/output/counts/uzb.89.counts inputs-uzb_vectors/counts/uzb.89.counts
ln -s /homes/egarnick/output/counts/uzb.90.counts inputs-uzb_vectors/counts/uzb.90.counts
ln -s /homes/egarnick/output/counts/uzb.91.counts inputs-uzb_vectors/counts/uzb.91.counts
ln -s /homes/egarnick/output/counts/uzb.92.counts inputs-uzb_vectors/counts/uzb.92.counts
ln -s /homes/egarnick/output/counts/uzb.93.counts inputs-uzb_vectors/counts/uzb.93.counts
ln -s /homes/egarnick/output/counts/uzb.94.counts inputs-uzb_vectors/counts/uzb.94.counts
ln -s /homes/egarnick/output/counts/uzb.95.counts inputs-uzb_vectors/counts/uzb.95.counts
ln -s /homes/egarnick/output/counts/uzb.96.counts inputs-uzb_vectors/counts/uzb.96.counts
ln -s /homes/egarnick/output/counts/uzb.97.counts inputs-uzb_vectors/counts/uzb.97.counts
ln -s /homes/egarnick/output/counts/uzb.98.counts inputs-uzb_vectors/counts/uzb.98.counts
ln -s /homes/egarnick/output/counts/uzb.99.counts inputs-uzb_vectors/counts/uzb.99.counts
ln -s /homes/egarnick/output/counts/uzb.100.counts inputs-uzb_vectors/counts/uzb.100.counts
