bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 0
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 1
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 2
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 3
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 4
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 5
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 6
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 7
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 8
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 9
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 10
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 11
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 12
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 13
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 14
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 15
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 16
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 17
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 18
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 19
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 20
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 21
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 22
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 23
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 24
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 25
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 26
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 27
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 28
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 29
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 30
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 31
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 32
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 33
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 34
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 35
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 36
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 37
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 38
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 39
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 40
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 41
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 42
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 43
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 44
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 45
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 46
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 47
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 48
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 49
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 50
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 51
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 52
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 53
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 54
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 55
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 56
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 57
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 58
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 59
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 60
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 61
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 62
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 63
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 64
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 65
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 66
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 67
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 68
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 69
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 70
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 71
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 72
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 73
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 74
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 75
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 76
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 77
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 78
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 79
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 80
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 81
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 82
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 83
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 84
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 85
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 86
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 87
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 88
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 89
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 90
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 91
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 92
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 93
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 94
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 95
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 96
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 97
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 98
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 99
bash /homes/egarnick/scripts/baseline/uzb_counts-m.sh 100
